const data = {
  FullName: "Trần Gia Nhuận",
  AGE: "28",
  Profile: "",
  GraduatedAt: "Da Nang College of Technology",
  Course: "2010-2013",
  Major: "Information Technology",
  "Graduation Thesis": "",
  Email: "gianhuan1211@gmail.com",
  Phone: "0702766468",
  Hobby: "Read technology news",
  Summary:
    "I have 8 years of web development expertise as a backend developer. I have participated in various projects including small and large undertakings over this time..",
  Skills: ["Php", "Nodejs", "Amazon Web Service", "Mysql", "MongoDB"],
  Projects: [
    {
      Name: "CenterPool",
      From: "01-2015 to 03-2015",
      Description: "Develop system Staff management",
      Responsibility: "DEV",
      DevelopEnvironment: "SQL, Java, JSF",
      TeamSize: "5",
    },
    {
      Name: "CLOUD_SOS012",
      From: "04-2015 to 05-2015",
      Description: "Migration data from system old to AWS",
      Responsibility: "DEV",
      DevelopEnvironment: "SQL Server 2003, 2008",
      TeamSize: "4",
    },
    {
      Name: "HRS.NET",
      From: "07-2015 to 11-2015",
      Description: "Create function for Car Auction system",
      Responsibility: "DEV",
      DevelopEnvironment: ".Net",
      TeamSize: "6",
    },
    {
      Name: "HATRS.J",
      From: "12-2015 to 04-2016",
      Description: "Development order and salse system",
      Responsibility: "DEV",
      DevelopEnvironment: "Oracle Database, Java, Struts",
      TeamSize: "4",
    },
    {
      Name: "CALIB",
      From: "06-2016 to 12-2016",
      Description: "Development and test for recruitment system",
      Responsibility: "DEV",
      DevelopEnvironment: "Oracle Database, Java, Struts",
      TeamSize: "15",
    },
    {
      Name: "Chatbot Web",
      From: "01-2017 to 09-2017",
      Description:
        "building chatbot system to automatically answer customers' questions for EC website",
      Responsibility: "DEV",
      DevelopEnvironment: "Laravel, vuejs, redis",
      TeamSize: "5",
    },
    {
      Name: "Internal Web (TMS)",
      From: "09-2017 to 04-2018",
      Description:
        "building an internal information management system of staff evaluating employee's ranking",
      Responsibility: "DEV",
      DevelopEnvironment: "Pure-code PHP, mysql, jquery",
      TeamSize: "3",
    },
    {
      Name: "analytics web",
      From: "07-2018 to 11-2018",
      Description:
        "Create an embedded script that collects user data such as site visits, boundrate measurements, which links are most  visited, etc ...",
      Responsibility: "DEV",
      DevelopEnvironment: "Laravel, mongoDB, jquery",
      TeamSize: "4",
    },
    {
      Name: "Video ondemand Web",
      From: "12-2018 to 09-2019",
      Description:
        "Build a system to help teachers create lessons so that students can learn, manage classrooms, manage videos, push notification, students can see what lessons they have learned, Watch the lectures of the instructor, etc...",
      Responsibility: "DEV",
      DevelopEnvironment: "Laravel, jquery,",
      TeamSize: "5",
    },
    {
      Name: "Server API of App",
      From: "01-2020 to 08-2020",
      Description:
        "Build an intermediary API system to connect client apps and third-party services, Customers can scan and buy products by qrcode right on the app, print reciept, track transactions for employees, create analysis chart, etc ...",
      Responsibility: "DEV",
      DevelopEnvironment: "Lumen, reactjs, aws sns, mysql",
      TeamSize: "5",
    },
    {
      Name: "Career-P",
      From: "09-2020 09-2022",
      Description:
        "Custom function in ec-cube ecommerce source, deploy batch to get product data, inventory quantity ..",
      Responsibility: "DEV",
      DevelopEnvironment: "PHP, Cake, Docker, mysql",
      TeamSize: "5",
    },
    {
      Name: "Eccube-M",
      From: "10-2022 04-2023",
      Description:
        "Custom function in ec-cube ecommerce source, deploy batch to get product data, inventory quantity ..",
      Responsibility: "DEV",
      DevelopEnvironment: "PHP, EC-CUBE, Docker, mysql, elasticsearch",
      TeamSize: "15",
    },
    {
      Name: "Career-L",
      From: "05-2023 10-2023",
      Description: "",
      Responsibility: "DEV",
      DevelopEnvironment: "Nodejs with Nestjs, mysql",
      TeamSize: "5",
    },
    {
      Name: "Wallet",
      From: "11-2023 09-2024",
      Description: "",
      Responsibility: "DEV",
      DevelopEnvironment: "Node with Nestjs, mysql",
      TeamSize: "15",
    },
  ],
};
